# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joonwoo3511/Mycode/SEAL-Bootstrapping

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joonwoo3511/Mycode/SEAL-Bootstrapping

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joonwoo3511/Mycode/SEAL-Bootstrapping/CMakeFiles /home/joonwoo3511/Mycode/SEAL-Bootstrapping//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joonwoo3511/Mycode/SEAL-Bootstrapping/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named a.out

# Build rule for target.
a.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 a.out
.PHONY : a.out

# fast build rule for target.
a.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/build
.PHONY : a.out/fast

Bootstrapper.o: Bootstrapper.cpp.o

.PHONY : Bootstrapper.o

# target to build an object file
Bootstrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Bootstrapper.cpp.o
.PHONY : Bootstrapper.cpp.o

Bootstrapper.i: Bootstrapper.cpp.i

.PHONY : Bootstrapper.i

# target to preprocess a source file
Bootstrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Bootstrapper.cpp.i
.PHONY : Bootstrapper.cpp.i

Bootstrapper.s: Bootstrapper.cpp.s

.PHONY : Bootstrapper.s

# target to generate assembly for a file
Bootstrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Bootstrapper.cpp.s
.PHONY : Bootstrapper.cpp.s

ModularReducer.o: ModularReducer.cpp.o

.PHONY : ModularReducer.o

# target to build an object file
ModularReducer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/ModularReducer.cpp.o
.PHONY : ModularReducer.cpp.o

ModularReducer.i: ModularReducer.cpp.i

.PHONY : ModularReducer.i

# target to preprocess a source file
ModularReducer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/ModularReducer.cpp.i
.PHONY : ModularReducer.cpp.i

ModularReducer.s: ModularReducer.cpp.s

.PHONY : ModularReducer.s

# target to generate assembly for a file
ModularReducer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/ModularReducer.cpp.s
.PHONY : ModularReducer.cpp.s

Point.o: Point.cpp.o

.PHONY : Point.o

# target to build an object file
Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Point.cpp.o
.PHONY : Point.cpp.o

Point.i: Point.cpp.i

.PHONY : Point.i

# target to preprocess a source file
Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Point.cpp.i
.PHONY : Point.cpp.i

Point.s: Point.cpp.s

.PHONY : Point.s

# target to generate assembly for a file
Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Point.cpp.s
.PHONY : Point.cpp.s

Polynomial.o: Polynomial.cpp.o

.PHONY : Polynomial.o

# target to build an object file
Polynomial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Polynomial.cpp.o
.PHONY : Polynomial.cpp.o

Polynomial.i: Polynomial.cpp.i

.PHONY : Polynomial.i

# target to preprocess a source file
Polynomial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Polynomial.cpp.i
.PHONY : Polynomial.cpp.i

Polynomial.s: Polynomial.cpp.s

.PHONY : Polynomial.s

# target to generate assembly for a file
Polynomial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Polynomial.cpp.s
.PHONY : Polynomial.cpp.s

Remez.o: Remez.cpp.o

.PHONY : Remez.o

# target to build an object file
Remez.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Remez.cpp.o
.PHONY : Remez.cpp.o

Remez.i: Remez.cpp.i

.PHONY : Remez.i

# target to preprocess a source file
Remez.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Remez.cpp.i
.PHONY : Remez.cpp.i

Remez.s: Remez.cpp.s

.PHONY : Remez.s

# target to generate assembly for a file
Remez.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Remez.cpp.s
.PHONY : Remez.cpp.s

func.o: func.cpp.o

.PHONY : func.o

# target to build an object file
func.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/func.cpp.o
.PHONY : func.cpp.o

func.i: func.cpp.i

.PHONY : func.i

# target to preprocess a source file
func.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/func.cpp.i
.PHONY : func.cpp.i

func.s: func.cpp.s

.PHONY : func.s

# target to generate assembly for a file
func.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/func.cpp.s
.PHONY : func.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... a.out"
	@echo "... Bootstrapper.o"
	@echo "... Bootstrapper.i"
	@echo "... Bootstrapper.s"
	@echo "... ModularReducer.o"
	@echo "... ModularReducer.i"
	@echo "... ModularReducer.s"
	@echo "... Point.o"
	@echo "... Point.i"
	@echo "... Point.s"
	@echo "... Polynomial.o"
	@echo "... Polynomial.i"
	@echo "... Polynomial.s"
	@echo "... Remez.o"
	@echo "... Remez.i"
	@echo "... Remez.s"
	@echo "... func.o"
	@echo "... func.i"
	@echo "... func.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

